name: Testing
on: [workflow_dispatch]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{github.ref}}
      - uses: actions/setup-node@v5
      - name: Run tests
        run: |
          ls -a
          npm i
          npm test